/** Every kind of picture DemoArt.tsx can draw. The demo-data seeder may only ask for these (a backend test checks). */
export const DEMO_ART_KINDS = [
  'backpack',
  'battery',
  'beanie',
  'blender',
  'book',
  'bottle',
  'cable',
  'camera',
  'chair',
  'charger',
  'chip',
  'desk',
  'dice',
  'dryer',
  'dumbbell',
  'earbuds',
  'fan',
  'gamepad',
  'headphones',
  'jar',
  'kettle',
  'keyboard',
  'lamp',
  'laptop',
  'microphone',
  'monitor',
  'mouse',
  'mug',
  'pan',
  'plug',
  'scarf',
  'shirt',
  'shoe',
  'speaker',
  'sunglasses',
  'tent',
  'toothbrush',
  'tripod',
  'trousers',
  'watch',
  'webcam',
] as const;

export type DemoArtKind = (typeof DEMO_ART_KINDS)[number];
