package com.pacific.marketplace.media;

import java.util.Optional;

/**
 * Where product photos are kept. Names are generated by the shop (never taken from the uploader), so a store can use
 * them as file names or object keys directly. Today it's the local disk; a cloud bucket can implement this later.
 */
public interface ImageStore {

    void save(String name, byte[] bytes);

    Optional<byte[]> load(String name);
}
